# Basic Information 
title: Xiaocan (Bruce) Li
position: Ph.D.
affiliation: University of Toronto
affiliation_link: https://d3m.mie.utoronto.ca/
# affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: hsiaotsan.li (at) mail.utoronto.ca

# Search Engine Optimization (SEO)
keywords: xiaocan li, li xiaocan, xiaocanli, xiaocan bruce li, lixiaocan
canonical: https://hsiaotsan.github.io
description: Xiaocan (Bruce) Li is a Ph.D. at the University of Toronto. His research focuses on using AI to solve real-world problems.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=0b7JUNQAAAAJ
cv_link: ./assets/Resume_Xiaocan_Bruce_Li.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/xiaocanli-uoft/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - blog/
  - .hugo_build.lock
  - hugo_stats.json
  - vendor/
  - node_modules/

# Keep Hugo blog output when Jekyll rebuilds
keep_files:
  - blog
